logging:
  level:
    ru.yandex.practicum: DEBUG

server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://postgres-ewm-main-db:5432/commerce_warehouse_db # Вариант 1: Использовать имя контейнера и внутренний порт (если запускаем в контейнере)
    url: jdbc:postgresql://localhost:5434/commerce_warehouse_db # Вариант 2: Использовать localhost и внешний порт (если запускаем на хосте)
    username: dbuser
    password: 123456


