logging:
  level:
    ru.yandex.practicum.aggregator: DEBUG

kafka:
  bootstrap-server: "localhost:9092"
  group_id: "group_01"
  topics:
    sensor: "telemetry.sensors.v1"
    snapshots: "telemetry.snapshots.v1"


