logging:
  level:
    ru.yandex.practicum.analyzer: DEBUG

kafka:
  hubEventsConsumer:
    bootstrapServer: "localhost:9092"
    client_id: "client_01"
    group_id: "group_02"
    topic: "telemetry.hubs.v1"
    maxPollIntervalMs : 1000
    pollTimeoutMs: 100
    enableAutoCommit: "false"
  snapshotsConsumer:
    bootstrapServer: "localhost:9092"
    client_id: "client_01"
    group_id: "group_03"
    topic: "telemetry.snapshots.v1"
    maxPollIntervalMs: 1000
    pollTimeoutMs: 100
    enableAutoCommit: "false"
  producer:
    bootstrapServer: "localhost:9092"
    topic: "telemetry.test.v1"

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://postgres-analyzer-db:5432/analyzerdb # Вариант 1: Использовать имя контейнера и внутренний порт (если запускаем в контейнере)
    url: jdbc:postgresql://localhost:5434/analyzerdb              # Вариант 2: Использовать localhost и внешний порт (если запускаем на хосте)
    username: dbuser
    password: 123456

grpc:
  client:
    hubrouter:
      address: 'localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext